import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import type { FC } from "react";
import { MainNav } from "@/components/main-nav";
import { UserMenu } from "@/components/user-menu";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const RootLayout: FC<LayoutProps<"/">> = ({ children }) => {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<div className="flex min-h-screen flex-col">
					<header className="sticky top-0 z-50 flex justify-center border-b bg-background backdrop-blur">
						<div className="mx-auto flex h-16 container w-full items-center justify-between">
							<MainNav />
							<UserMenu />
						</div>
					</header>
					{children}
				</div>
			</body>
		</html>
	);
};

export default RootLayout;
